config/routes.rb
TaskServer::Application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#logout'

  resources :sessions, only: [:new, :create]
  resources :jobs
  get 'jobs/:id/execute' =>  'jobs#execute'
  resources :schedules
  resources :job_logs

end

app/models/job.rb
require 'debugger'
class Job < ActiveRecord::Base
  belongs_to :schedule
  has_many :job_logs

  validates :name, uniqueness: true
  validates :name, :command, presence: true

  after_save { self.schedule ? self.execute : Resque.remove_schedule(self.name) }
  before_destroy { Resque.remove_schedule(self.name) }

  def execute
    job_options_hash = {
      :id => self.id,
      :name => self.name,
      :command => self.command,
      :schedule => self.schedule.name
    }

    config = {
      :class => 'ResqueWorker',
      :args => job_options_hash,
      :cron => self.schedule.cron_string,
      :queue => 'high',
      :persist => true
    }

    Resque.set_schedule(self.name, config)
  end
end

app/models/job_log.rb
class JobLog < ActiveRecord::Base
  belongs_to :job
end

app/models/resque_worker.rb
require 'debugger'
class ResqueWorker < ActiveRecord::Base
  @queue = :high

  def self.perform(job_options)
    # job_options comes in as JSON
    success_result = system(job_options["command"])
    @job = Job.find(job_options["id"])
    JobLog.create(job: @job,
                  name: job_options["name"],
                  command: job_options["command"],
                  schedule: job_options["schedule"],
                  success: success_result)
  end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :jobs
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session[:user_id]) if session[:user_id]
  end
end

app/controllers/job_logs_controller.rb
class JobLogsController < ApplicationController
  def index
    @job_logs = JobLog.all
  end
end

app/controllers/jobs_controller.rb
require 'debugger'
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.create(name: params[:job][:name], command: params[:job][:command])
    redirect_to job_path(@job)
  end

  def update
    @job = Job.find(params[:id])
    if params[:job]["schedule_id"] == ""
      @schedule = nil
    else
      @schedule = Schedule.find(params[:job]["schedule_id"])
    end
      @job.update(name: params[:job][:name],
        command: params[:job][:command],
        schedule: @schedule)
    redirect_to job_path(@job)
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.create(name: params[:schedule][:name], cron_string: params[:schedule][:cron_string])
    redirect_to schedule_path(@schedule)
  end

  def update
    @schedule = Schedule.find(params[:id])
    @schedule.update(name: params[:schedule][:name], cron_string: params[:schedule][:cron_string])
    redirect_to schedule_path(@schedule)
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to schedules_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @scheduled_jobs = Job.select {|j| j.schedule }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/job_logs/index.html.erb
<h1>Job History</h1>
<% if current_user %>

<% if @job_logs.empty? %>
Empty job history
<% else %>
  <table>
    <tr>
      <th>Name</th>
      <th>Datetime ran</th>
      <th>Ran Successfully?</th>
    </tr>
  <% @job_logs.each do |log| %>
    <tr>
      <td><%= log.name %></td>
      <td><%= log.created_at %></td>
      <td><%= log.success %></td>
    </tr>
    <% end %>
  </table>
<% end %>

<% else %>
Not logged in
<% end %>

<p><%= link_to "Back", root_path %></p>

app/views/jobs/edit.html.erb
<%= form_for @job, url: {action: "update"} do |f| %>
  <p><%= f.text_field(:name, placeholder: @job.name)  %></p>
  <p><%= f.text_field(:command, placeholder: @job.command) %></p>
  <p>Schedule: <%= collection_select(:job, :schedule_id, Schedule.all, :id, :name, {include_blank: "None"} ) %></p>
  <%= link_to "Back", job_path(@job) %>
  <%= f.submit "Save" %>
  <% end %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<% if current_user %>
<!-- JobWorker.perform_async("bob", 5") -->

<ul>
  <% @jobs.each do |job| %>
  <li> <%= link_to job.name, job %></li>
  <% end %>
</ul>
<p><%= link_to "Create New Job", new_job_path %></p>
<p><%= link_to "Back", root_path %></p>

<% else %>
<h1>not logged in</h1>
<% end %>

app/views/jobs/new.html.erb
<h1>Create New Job</h1>

<%= form_for @job, url: {action: "create"} do |f| %>
  <p><%= f.text_field(:name, placeholder: "Name")  %></p>
  <p><%= f.text_field(:command, placeholder: "Shell Command") %></p>
  <p>Schedule: <%= collection_select(:job, :schedule_id, Schedule.all, :id, :name, include_blank: "None") %></p>
  <p><%= link_to "Back", job_path(@job) %>
  <%= f.submit "Create Job" %>
  <% end %>

app/views/jobs/show.html.erb
<h1>Job Info</h1>
  <p>Name: <%= @job.name %></p>
  <p>Command to be run: <%= @job.command %></p>
  <p>Schedule:
    <% if @job.schedule.nil? %>
    <%= "Not scheduled" %>
    <% else %>
    <%= "#{@job.schedule.name}, #{@job.schedule.cron_string}" %>
    <% end %></p>
    <%= link_to "Back", jobs_path %>
  <%= link_to "Edit", edit_job_path(@job) %>
  <%= button_to "Delete Job", job_path(@job), method: "delete", data: {confirm: "Really delete job?", disable_with: "Deleting..."} %>

  <div class="job-logs">
    <h3>Job History</h3>
    <% if @job.job_logs.empty? %>
    <P>No job history</p>
      <% else %>
      <table>
        <tr>
          <th>Name</th>
          <th>Datetime ran</th>
          <th>Success</th>
        </tr>
        <% @job.job_logs.each do |job_log| %>
        <tr>
          <td><%= job_log.name %></td>
          <td><%= job_log.created_at %></td>
          <td><%= job_log.success %></td>
        </tr>
        <% end %>
      </table>
      <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job Scheduler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "normalize", media: "all", "data-turbo-links-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "shared/nav" %>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/schedules/edit.html.erb
<h1>Edit Schedule</h1>

<%= form_for @schedule, url: {action: "update"} do |f| %>
  <p><%= f.text_field(:name, placeholder: @schedule.name)  %></p>
  <p><%= f.text_field(:cron_string, placeholder: @schedule.cron_string) %></p>
  <%= link_to "Back", schedule_path(@schedule) %>
  <%= f.submit "Save Schedule" %>
  <% end %>

app/views/schedules/index.html.erb
<h1>Schedules</h1>

<% if current_user %>
<!-- JobWorker.perform_async("bob", 5") -->

<ul>
  <% @schedules.each do |schedule| %>
  <li> <%= link_to schedule.name, schedule %></li>
  <% end %>
</ul>
<p><%= link_to "Create New Schedule", new_schedule_path %></p>
<p><%= link_to "Back", root_path %></p>

<% else %>
<h1>not logged in</h1>
<% end %>

app/views/schedules/new.html.erb
<h1>Create new schedule</h1>

<%= form_for @schedule, url: {action: "create"} do |f| %>
  <p><%= f.text_field(:name, placeholder: "Name")  %></p>
  <p><%= f.text_field(:cron_string, placeholder: "cron string") %></p>
  <%= link_to "Back", schedule_path(@schedule) %>
  <%= f.submit "Create Schedule" %>
  <% end %>

app/views/schedules/show.html.erb
<h1>Schedule Info</h1>

<p>Name: <%= @schedule.name %></p>
<p>Cron String: <%= @schedule.cron_string %></p>
<p><%= link_to "Back", schedules_path %>
  <%= link_to "Edit", edit_schedule_path(@schedule) %>
  <%= button_to "Delete Schedule", schedule_path(@schedule), method: "delete", data: {confirm: "Really delete schedule?", disable_with: "Deleting..."} %>
</p>

app/views/shared/_nav.html.erb
<div class="nav">
  <ul>
    <li><div id="title"><%= link_to "Job Scheduler", root_path %></div></li>
    <% if current_user %>
    <li>Current user: <%= current_user.email %></li>
    <li><a href="/logout">Logout</a></li>
    <% else %>
    <li><a href="/login">Login</a></li>
    <% end %>
  </ul>
</div>
</div>

app/views/welcome/index.html.erb
<% if current_user %>
<div class="scheduled_jobs">
  <% if @scheduled_jobs.nil? %>
  p  @scheduled_jobs
  No scheduled jobs
  <% else %>

  <p>
    <%= link_to 'Jobs', jobs_path %>
  </p>
  <p><%= link_to 'Schedules', schedules_path %></p>

  <p>
    <%= link_to 'Job Log', job_logs_path %>
  </p>


  <h3> Scheduled Jobs</h3>
  <table>
    <tr>
      <th>Name</th>
      <th>Schedule</th>
    </tr>
    <% @scheduled_jobs.each do |job| %>
    <tr>
      <td><%= link_to job.name, job_path(job) %>
        <td><%= link_to job.schedule.name, schedule_path(job.schedule) %></td>
      </tr>
      <% end %>
    </table>
    <% end %>
  </div>



  <% else %>
  Not logged in
  <% end %>